version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 4443:4443
      - 9002:9002
      - 8883:8883
    volumes:
      -  ./certs:/var/lib/certs/
      - ./rabbitmq/volumes:/var/lib/rabbitmq/
      - ./rabbitmq/conf:/etc/rabbitmq/
